// profile
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const SAVE_PROFILE = 'SAVE_PROFILE';

export enum ActionTypes {
  // app
  SET_MESSAGES = 'SET_MESSAGES',
  CLEAR_ALL_MESSAGES = 'CLEAR_ALL_MESSAGES',
  FETCH_SETTINGS = 'FETCH_SETTINGS',
  SAVE_SETTINGS = 'SAVE_SETTINGS',
  LOGIN = 'LOGIN',
  // invoices
  FETCH_INVOICES = 'FETCH_INVOICES',
  RESET_CURRENT_INVOICE = 'RESET_CURRENT_INVOICE',
  FETCH_INVOICE = 'FETCH_INVOICE',
  FETCH_INVOICE_LOCALES = 'FETCH_INVOICE_LOCALES',
  DELETE_INVOICE = 'DELETE_INVOICE',
  SAVE_INVOICE = 'SAVE_INVOICE',
  DOWNLOAD_INVOICE_PDF = 'DOWNLOAD_INVOICE_PDF',
}
