// app
export const SET_MESSAGES = 'SET_MESSAGES';
export const CLEAR_ALL_MESSAGES = 'CLEAR_ALL_MESSAGES';

// invoices
export const FETCH_INVOICES = 'FETCH_INVOICES';
export const RESET_CURRENT_INVOICE = 'RESET_CURRENT_INVOICE';
export const FETCH_INVOICE = 'FETCH_INVOICE';
export const DELETE_INVOICE = 'DELETE_INVOICE';
export const SAVE_INVOICE = 'SAVE_INVOICE';
export const DOWNLOAD_INVOICE_PDF = 'DOWNLOAD_INVOICE_PDF';
