// app
export const SET_MESSAGES = 'SET_MESSAGES';
export const CLEAR_ALL_MESSAGES = 'CLEAR_ALL_MESSAGES';
export const FETCH_SETTINGS = 'FETCH_SETTINGS';
export const SAVE_SETTINGS = 'SAVE_SETTINGS';
export const LOGIN = 'LOGIN';

// invoices
export const FETCH_INVOICES = 'FETCH_INVOICES';
export const RESET_CURRENT_INVOICE = 'RESET_CURRENT_INVOICE';
export const FETCH_INVOICE = 'FETCH_INVOICE';
export const FETCH_INVOICE_LOCALES = 'FETCH_INVOICE_LOCALES';
export const DELETE_INVOICE = 'DELETE_INVOICE';
export const SAVE_INVOICE = 'SAVE_INVOICE';
export const DOWNLOAD_INVOICE_PDF = 'DOWNLOAD_INVOICE_PDF';

// profile
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const SAVE_PROFILE = 'SAVE_PROFILE';
